version: '2'

services:
  apache:
    image: bitnami/apache
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - ./../build/:/app
    # environment:
    #  - VIRTUAL_HOST=boilerplate.com